# Generated by Django 4.2 on 2025-01-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'UrlShortener',
                'verbose_name_plural': 'UrlShorteners',
                'ordering': ['-created'],
            },
        ),
    ]
